# Generated by Django 4.0.3 on 2022-04-09 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pizza_app.home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_name', models.CharField(max_length=30)),
                ('sauce', models.CharField(blank=True, max_length=30, null=True)),
                ('products', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sauce', models.CharField(blank=True, choices=[('tomato sauce', 'tomato sauce'), ('BBQ sauce', 'BBQ sauce'), ('sweet pizza sauces', 'sweet pizza sauces'), ('pesto sauce', 'pesto sauce')], max_length=18, null=True)),
                ('cheese', models.CharField(blank=True, max_length=50, null=True, validators=[pizza_app.home.models.validate_cheese])),
                ('meat', models.CharField(blank=True, max_length=50, null=True, validators=[pizza_app.home.models.validate_meat])),
                ('additional', models.CharField(blank=True, max_length=50, null=True, validators=[pizza_app.home.models.validate_add])),
                ('price', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.order')),
                ('pizza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.pizzaitem')),
            ],
        ),
    ]
