# Generated by Django 4.0.3 on 2022-04-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_drink_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderd',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
