# Generated by Django 4.0.3 on 2022-04-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_orderitem_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='orderdrink',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
