# Generated by Django 4.0.3 on 2022-04-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_pizza_complete_alter_orderdrink_complete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Pizza Create', max_length=50)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('total', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
