# Generated by Django 4.0.3 on 2022-04-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_completeorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeorder',
            name='name',
            field=models.CharField(blank=True, default='Pizza Create', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='completeorder',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
