# Generated by Django 4.0.3 on 2022-04-15 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_completeorder_order_id_alter_completeorder_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completeorder',
            old_name='order_id',
            new_name='order',
        ),
    ]
