# Generated by Django 4.0.3 on 2022-04-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_order_id_completeorder_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinformation',
            name='order_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderinformation',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
