# Generated by Django 4.0.3 on 2022-04-15 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_completeorder_image_remove_completeorder_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeorder',
            name='user',
        ),
        migrations.AddField(
            model_name='completeorder',
            name='pizza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.orderitem'),
        ),
    ]
