# Generated by Django 4.0.3 on 2022-04-15 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0020_remove_completeorder_user_completeorder_pizza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeorder',
            name='pizza',
        ),
        migrations.AddField(
            model_name='completeorder',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completeorder',
            name='name',
            field=models.CharField(blank=True, default='Pizza Create', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='completeorder',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completeorder',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='completeorder',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completeorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderinformation',
            name='order_number',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderinformation',
            name='total',
            field=models.IntegerField(),
        ),
    ]
