# Generated by Django 4.0.3 on 2022-04-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_orderinformation_order_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='sauce',
            field=models.CharField(choices=[('tomato sauce', 'tomato sauce'), ('BBQ sauce', 'BBQ sauce'), ('sweet pizza sauces', 'sweet pizza sauces'), ('pesto sauce', 'pesto sauce')], max_length=18),
        ),
    ]
